spring:
  # ─────────────────────── POSTGRESQL (Neon) ───────────────────────
  datasource:
    url: ${DB_URL}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update              # створює/оновлює таблиці автоматично
    show-sql: true                # SQL-запити в консолі
    properties:
      hibernate:
        format_sql: true          # гарний вивід SQL
        use_sql_comments: true    # коментарі в SQL

  # ─────────────────────── LOGGING (щоб бачити запити) ───────────────────────
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE   # показує значення параметрів ? в запитах
    com.example.step_project_beck_spring: DEBUG

# ─────────────────────── SERVER ──────────────────────
server:
  port: 9000

# ─────────────────────── CLOUDINARY - image upload ──────────────────────

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}

