server:
  port: ${PORT:9000}

# ─────────────────────── CLOUDINARY ──────────────────────
cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}

# ─────────────────────── SPRING CONFIG ──────────────────────
spring:
  application:
    name: Step_project_beck_spring

  # Налаштування бази даних
  datasource:
    url: ${DB_URL}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  # Налаштування Hibernate
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:465}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    protocol: smtps
    properties:
      mail:
        transport:
          protocol: smtps
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true
            trust: "*"
  # OAuth2
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}          # з Google Cloud Console
            client-secret: ${GOOGLE_CLIENT_SECRET}  # з Google Cloud Console
            scope: openid,email,profile
            redirect-uri: "https://step-project-api.onrender.com/login/oauth2/code/google"

        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub
  # Local host front
application:
  frontend-url: ${FRONTEND_URL:http://localhost:5173} #Локально це буде localhost:5173, а на Render ми змінимо це через змінні середовища
# ─────────────────────── JWT ───────────────────────
jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}
  long-expiration: ${JWT_LONG_EXPIRATION}

# ─────────────────────── LOGGING ───────────────────────
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.example.step_project_beck_spring: DEBUG
    org.springframework.security: DEBUG
    org.springframework.boot.autoconfigure.security: DEBUG
    org.springframework.boot.autoconfigure.security.oauth2: DEBUG

# ─────────────────────── FIREBASE ───────────────────────

firebase:
  web-api-key: ${FIREBASE_API_KEY}