# ─────────────────────── SERVER ──────────────────────
server:
  port: 9000

# ─────────────────────── CLOUDINARY ──────────────────────
cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}

# ─────────────────────── SPRING CONFIG ──────────────────────
spring:
  # Налаштування бази даних
  datasource:
    url: jdbc:postgresql://ep-ancient-band-adea5qk2-pooler.c-2.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
    driver-class-name: org.postgresql.Driver
    username: neondb_owner
    password: npg_uteRxP3B8Oor

  # Налаштування Hibernate
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update          # Онова таблиці (було validate - краще update для розробки)
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: galaykseniia@gmail.com
    password: slmnnamangrccolj
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# ─────────────────────── LOGGING ───────────────────────
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.example.step_project_beck_spring: DEBUG