server:
  port: 9000

# ─────────────────────── CLOUDINARY ──────────────────────
cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}

# ─────────────────────── SPRING CONFIG ──────────────────────
spring:
  application:
    name: Step_project_beck_spring

  # Налаштування бази даних
  datasource:
    url: ${DB_URL}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  # Налаштування Hibernate
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # Налаштування пошти
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  # Jwt Settings
jwt:
  # Ключ (з дефолтним значенням для локального запуску)
  secret: ${JWT_SECRET:662E635266556A586E3272357538782F413F4428472B4B6250645367566B59703373367639792F423F4528482B4D6251}
  expiration: ${JWT_EXPIRATION:900000}
  long-expiration: ${JWT_LONG_EXPIRATION:604800000}
# ─────────────────────── LOGGING ───────────────────────
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.example.step_project_beck_spring: DEBUG